version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: db
  app:
    image: my-node-app
    ports:
      - "13000:3000"
