POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query": "query { getUser(email: \"test@gmail.com\") { firstName, lastName } }"
}

###

POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query": "query { getAllUsers { firstName, lastName } }"
}

###

POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query": "query { getPosts(email: \"test@gmail.com\") { title authorId author { email } } }"
}

###

POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query": "mutation { createUser(firstName: \"Bob\", lastName: \"Bobblehead\", email: \"bob@gmail.com\", password: \"password\") { success, message, token, user { email, password } } }"
}

###

POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query": "mutation { loginUser(email: \"bob@gmail.com\", password: \"password\") { success, message, token, user { firstName, lastName, email, password } }  }"
}

###

POST http://localhost:4000/graphql
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc1OTM2OTY5NSwiZXhwIjoxNzU5MzczMjk1fQ.qr-yilX85uJPbiC3RuL9yZ9n7v_uKUAm7OW6fcSihKQ

{
    "query": "query { me { firstName, lastName, email, password } }"
}

###
POST http://localhost:4000/graphql
Content-Type: application/json

{
    "query": "mutation { createPost(email: \"bob@gmail.com\", password: \"password\", title: \"apiTest2\") { title authorId } }"
}